package com.planed.ctlBot.common;

public enum GameStatus {
    CHALLENGE_EXTENDED,
    CHALLENGE_ACCEPTED,
    PARTIALLY_REPORTED,
    CONFLICT_STATE,
    CHALLENGE_REJECTED,
    CHALLENGE_REVOKED,
    GAME_PLAYED
}
